require "user.options"
require "user.keymaps"
require "user.packerbootstrap"    -- Must come before plugins
require "user.plugins"
require "user.theme"
require "user.whichkey"
require "user.filetree"
require "user.terminal"
require "user.navigation"
require "user.coding"
